#!/usr/bin/env bash
source "/home/andy/.cache/wal/colors.sh"
# this is a simple config for herbstluftwm

cmds=()
#hc() {
#    herbstclient "$@"
#}
hc() {
     cmds+=(";" "$@")
}

hc emit_hook reload

# remove all existing keybindings
hc keyunbind --all

# keybindings
# if you have a super key you will be much happier with Mod set to Mod4
Mod=Mod4   # Use the super key as the main modifier

hc keybind $Mod-Control-e quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-q close_and_remove
hc keybind $Mod-e close
hc keybind $Mod-Return spawn "${TERMINAL:-urxvt}" # use your $TERMINAL with xterm as fallback
hc keybind $Mod-Shift-Return spawn termite

# basic movement
# focusing clients
hc keybind $Mod-Left  focus left
hc keybind $Mod-Down  focus down
hc keybind $Mod-Up    focus up
hc keybind $Mod-Right focus right
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right

# moving clients
hc keybind $Mod-Shift-Left  shift left
hc keybind $Mod-Shift-Down  shift down
hc keybind $Mod-Shift-Up    shift up
hc keybind $Mod-Shift-Right shift right
hc keybind $Mod-Shift-h     shift left
hc keybind $Mod-Shift-j     shift down
hc keybind $Mod-Shift-k     shift up
hc keybind $Mod-Shift-l     shift right

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-u       split   bottom  0.5
hc keybind $Mod-Shift-u split   top     0.5
hc keybind $Mod-o       split   right   0.5
hc keybind $Mod-Shift-o split   left    0.5
# let the current frame explode into subframes
hc keybind $Mod-Control-space split explode

# resizing frames
resizestep=0.05
hc keybind $Mod-Control-h       resize left +$resizestep
hc keybind $Mod-Control-j       resize down +$resizestep
hc keybind $Mod-Control-k       resize up +$resizestep
hc keybind $Mod-Control-l       resize right +$resizestep
hc keybind $Mod-Control-Left    resize left +$resizestep
hc keybind $Mod-Control-Down    resize down +$resizestep
hc keybind $Mod-Control-Up      resize up +$resizestep
hc keybind $Mod-Control-Right   resize right +$resizestep

# tags
tag_names=( {1..9} )
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in "${!tag_names[@]}" ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
# make firefox fullscreen in frame
hc keybind $Mod-Shift-f chain , attr clients.focus.ewmhnotify false , attr clients.focus.fullscreen false , attr clients.focus.ewmhnotify true
hc keybind $Mod-t pseudotile toggle
# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod-space                                                           \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 vertical horizontal max vertical grid    \
               , cycle_layout +1

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-i jumpto urgent

# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color "$color2"
hc set frame_border_normal_color '#717475'
hc set frame_bg_normal_color '#717475'
hc set frame_bg_active_color "$color2"
hc set frame_border_width 1
hc set always_show_frame 0
hc set frame_bg_transparent 1
hc set frame_transparent_width 1
hc set frame_gap 4

hc attr theme.active.color "$color2"
hc attr theme.normal.color '#717475'
hc attr theme.urgent.color red
hc attr theme.inner_width 1
hc attr theme.inner_color black
hc attr theme.border_width 3
hc attr theme.floating.border_width 4
hc attr theme.floating.outer_width 1
hc attr theme.floating.outer_color black
hc attr theme.active.inner_color "$color2"
hc attr theme.active.outer_color "$color2"
hc attr theme.background_color '#717475'

hc set window_gap 0
hc set window_border_inner_width 0
hc set frame_padding 0
hc set frame_gap 30
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 0
hc set mouse_recenter_gap 0

# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off
hc rule class~'[Pp]olybar' manage=off
hc rule class='Pinentry' pseudotile=on

# unlock, just to be sure
hc unlock

herbstclient set tree_style '╾│ ├└╼─┐'

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
hc detect_monitors
hc pad 0 35 0 0

hc keybind $Mod-d spawn dmenu_run_hlwm -nb "$color0" -nf "$color15" -sb "$color1" -sf "$color15" -b -fn 'Dina-12'
#hc keybind $Mod-Shift-d spawn ~/.scripts/rofi_run_hlwm
hc keybind $Mod-Control-p spawn ~/.scripts/passmenu --browse -nb "$color0" -nf "$color15" -sb "$color1" -sf "$color15" -b -fn 'Dina-12'
hc keybind $Mod-Shift-p spawn ~/.scripts/passmenu --type --get user:password --enter -nb "$color0" -nf "$color15" -sb "$color1" -sf "$color15" -b -fn 'Dina-12'
hc keybind $Mod-p spawn ~/.scripts/passmenu -nb "$color0" -nf "$color15" -sb "$color1" -sf "$color15" -b -fn 'Dina-12'
hc keybind $Mod-q spawn qutebrowser
hc keybind $Mod-Shift-m spawn wal -i /home/andy/Pictures/walls -q
hc keybind $Mod-Shift-s spawn spotify
hc keybind $Mod-z spawn zathura
hc keybind XF86AudioLowerVolume spawn /usr/bin/pactl set-sink-volume @DEFAULT_SINK@ '-5%'
hc keybind XF86AudioRaiseVolume spawn /usr/bin/pactl set-sink-volume @DEFAULT_SINK@ '+5%'
hc keybind XF86AudioMute spawn /usr/bin/pactl set-sink-mute @DEFAULT_SINK@ toggle
hc keybind $Mod-Control-i spawn ~/.scripts/i3lock-fancysm -f ~/.startpage/dina10px.ttf

hc keybind Print chain , spawn scrot ~/Pictures/scrot/hlwm_scrot_%m_%d_%Y_%T.png , spawn sleep 3 , spawn notify-send 'Screenshot Taken.'

hc keybind XF86AudioPlay spawn playerctl play-pause
hc keybind XF86AudioPause spawn playerctl play-pause
hc keybind XF86AudioNext spawn playerctl next
hc keybind XF86AudioPrev spawn playerctl previous

hc set focus_follows_mouse 1

herbstclient chain "${cmds[@]}"
# find the panel
#panel=~/.config/herbstluftwm/panel.sh
#[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
#for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
#    # start it on each monitor
#    "$panel" $monitor &
#done

if ! pgrep -x urxvtd >/dev/null; then
    urxvtd -f -q -o &
fi
xset -b
killall dunst
dunst &
synclient TouchpadOff=1
killall polybar
polybar herb &
