c = c  # noqa: F821
config = config  # noqa: F821
# Autogenerated config.py
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

# Uncomment this to still load settings configured via autoconfig.yml
# config.load_autoconfig()

# Hide the statusbar unless a message is shown.
# Type: Bool
c.statusbar.hide = False

# When to show the tab bar.
# Type: String
# Valid values:
#   - always: Always show the tab bar.
#   - never: Always hide the tab bar.
#   - multiple: Hide the tab bar if only one tab is open.
#   - switching: Show the tab bar when switching tabs.
c.tabs.show = 'always'

config.set('url.default_page', 'https://archlinux.org')
config.set('url.start_pages', 'https://archlinux.org')
config.set('editor.command', ['urxvtc', '-e', 'vim', '{}'])
config.set('content.private_browsing', True)
config.set('content.xss_auditing', True)
config.set('content.headers.accept_language', 'en-US,en;q=0.5')
config.set('content.headers.user_agent', 'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0')
config.set('tabs.background', True)
config.set('content.webgl', False)
config.set('url.searchengines', {"DEFAULT": "https://www.perfectpixel.de/searx/?q={}", "startpage": "https://www.startpage.com/do/dsearch?query={}&cat=web&pl=opensearch&language=english", "arch": "https://wiki.archlinux.org/index.php?title=Special:Search&search={}", "aur": "https://aur.archlinux.org/packages/?O=0&K={}", "youtube": "https://www.youtube.com/results?search_query={}&page={{startPage?}}&utm_source=opensearch", "google": "https://www.google.com/search?hl=en&q={}"})
config.bind('zm', 'spawn mpv {url}')
config.bind('zM', 'hint links spawn mpv {hint-url}')
config.bind('zf', 'spawn feh {url}')
config.bind('zF', 'hint links spawn feh {hint-url}')
config.unbind('d', mode='normal')
config.unbind('u', mode='normal')
config.bind('d', 'scroll-page 0 0.5')
config.bind('u', 'scroll-page 0 -0.5')
config.unbind('<Ctrl-d>', mode='normal')
config.unbind('<Ctrl-u>', mode='normal')
config.bind('<Ctrl-d>', 'tab-close')
config.bind('<Ctrl-u>', 'undo')
config.unbind('J', mode='normal')
config.unbind('K', mode='normal')
config.bind('J', 'tab-prev')
config.bind('K', 'tab-next')
