#!/usr/bin/env bash
# Copy of dmenu_run_hlwm for Rofi

if ! command -v rofi > /dev/null 2>/dev/null ; then
	echo "Error: Requirement rofi not found in your PATH." >&2
	exit 1
fi

# Get the currently active tag
tag=$(herbstclient attr tags.focus.name)

# Prints the path of the binary in path selected by rofi
rofiPrintPath() {
	cachedir=${XDG_CACHE_HOME:-"$HOME/.cache"}
	if [ -d "$cachedir" ]; then
		cache=$cachedir/rofi-3.runcache
		hlwmcache=$cachedir/rofi-hlwm.runcache
	else
		cache=$HOME/.rofi_cache # if no xdg dir, fall back to dotfile in ~
	fi
	IFS=:
	if stest -dqr -n "$hlwmcache" "$PATH"; then
		cut -d ' ' -f2 "$cache" | tee "$hlwmcache" | rofi -dmenu -p 'run: ' "$@"
	else
		rofi -dmenu -p 'run: ' "$@" < "$hlwmcache"
	fi
}

selectedPath=$(rofiPrintPath)

# Ensure that the tag exists
herbstclient add "$tag"

# Move next window from this process to this tag. Prepend the rule so
# that it may be overwritten by existing custom rules e.g. in the
# autostart. Also set a maximum age for this rule of 120 seconds and
# mark it as one-time-only rule.
herbstclient rule prepend maxage="120" pid="$$" tag="$tag" once

exec "$selectedPath"
