#!/usr/bin/env bash
source "${HOME}/.cache/wal/colors.sh"

reload_poly(){
    pkill polybar && polybar i3 &
}

reload_dunst() {
    pkill dunst && \
        dunst \
            -lb "#000000" \
            -nb "#000000" \
            -cb "#000000" \
            -lf "$color2"  \
            -bf "$color2"  \
            -cf "#e2465b" &
}

main() {
    reload_dunst &
}

main >/dev/null 2>&1
